include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Reglas recomendadas para Flutter
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true
    avoid_unnecessary_containers: true
    use_key_in_widget_constructors: true
    prefer_single_quotes: false
    always_declare_return_types: true
    avoid_print: true
    prefer_typing_uninitialized_variables: true
